name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app for GitHub Pages
        run: npm run build -- --configuration production --base-href /

      - name: Copy index.html to 404.html (for Angular routing)
        run: cp dist/grow-together2/browser/index.html dist/grow-together2/browser/404.html

      - name: List dist folder contents
        run: ls -R dist

      - name: Deploy Angular app to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/grow-together2/browser
          cname: growtogether2.cadiumdev.com
